spring:
  application:
    name: ${APP_NAME}
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: ${APP_PORT}
